
Program ini dibuat untuk melakukan automatisasi pengolahan (cleaning) data text yang berguna untuk pemodelan model analisa sentimen.

import pandas dan numpy untuk cleaning

In [ ]:
import pandas as pd
import numpy as np

memasukan data csv ke vsc untuk di cleaning

In [ ]:
df = pd.read_csv('osn.csv', low_memory=False)

df

,Unnamed: 0,Nama Peserta,Gender,Sekolah,Provinsi,Kab/Kota,Bidang,Jenjang Lomba,Jenjang Sekolah,Kelas,Medali,Prize Tambahan,Tahun
0,0,Gangsar Lintas Damai,L,MA Amanatul Ummah,Jawa Timur,Kota Surabaya,Biologi,SMA,SMA,11.0,Partisipan,NaN,2016
1,1,Muhammad Khairul Ihsan,L,MAN 1 Banda Aceh,Aceh,Kota Banda Aceh,Ekonomi,SMA,SMA,11.0,Partisipan,NaN,2021
2,2,Farhannur,L,MAN 1 Banda Aceh,Aceh,Kota Banda Aceh,Ekonomi,SMA,SMA,11.0,Emas,NaN,2022
3,3,Muhammad Fathoni,L,MAN 1 Banda Aceh,Aceh,Kota Banda Aceh,Fisika,SMA,SMA,11.0,Partisipan,NaN,2022
4,4,Rahmat MI,L,MAN 1 Banda Aceh,Aceh,Kota Banda Aceh,Kimia,SMA,SMA,11.0,Partisipan,NaN,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19322,19322,Fitri Julia Simamora,P,SMPN 4 Doloksanggul,Sumatera Utara,Kab. Humbang Hasundutan,Matematika,SMP,SMP,7.0,Partisipan,NaN,2024
19323,19323,Jonathan Kevin Aruan,L,SMPN 6 Sentajo,Riau,Kab. Kuantan Singingi,IPS,SMP,SMP,NaN,Partisipan,NaN,2016
19324,19324,Mely Winda Sihite,P,SMPN 4 Doloksanggul,Sumatera Utara,Kab. Humbang Hasundutan,Matematika,SMP,SMP,7.0,Partisipan,NaN,2024
19325,19325,Jelita Fazira,P,SMPN 4 Pantai Labu Satu Atap,Sumatera Utara,Kab. Deli Serdang,IPS,SMP,SMP,NaN,Partisipan,NaN,2021
19326,19326,Pether Kanisius Gajah,L,SMPN 4 Parlilitan,Sumatera Utara,Kab. Humbang Hasundutan,IPS,SMP,SMP,NaN,Partisipan,NaN,2020

melakukan penghapusan baris pada data yang kolom kelasnya kosong atau missing value

In [11]:
df = df.dropna(subset=['Kelas'])

melakukan pengisian data pada baring baring missing value pada kolom prize tambahan

In [16]:
df['Prize Tambahan'] = df['Prize Tambahan'].fillna('Tidak Ada')

melihat jumlah data, keterangan tipe data agar sesuai

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 14852 entries, 0 to 19324
Data columns (total 13 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       14852 non-null  int64
 1   Nama Peserta     14852 non-null  object
 2   Gender           14852 non-null  object
 3   Sekolah          14852 non-null  object
 4   Provinsi         14852 non-null  object
 5   Kab/Kota         14852 non-null  object
 6   Bidang           14852 non-null  object
 7   Jenjang Lomba    14852 non-null  object
 8   Jenjang Sekolah  14852 non-null  object
 9   Kelas            14852 non-null  float64
 10  Medali           14852 non-null  object
 11  Prize Tambahan   14852 non-null  object
 12  Tahun            14852 non-null  int64
dtypes: float64(1), int64(2), object(10)
memory usage: 1.6+ MB

menghilangkan duplikat pada data (jika ada)

In [14]:
df = df.drop_duplicates()

melihat panjangnya data

In [15]:
print(len(df))

14852

data final setelah di cleaning

In [17]:
df

,Unnamed: 0,Nama Peserta,Gender,Sekolah,Provinsi,Kab/Kota,Bidang,Jenjang Lomba,Jenjang Sekolah,Kelas,Medali,Prize Tambahan,Tahun
0,0,Gangsar Lintas Damai,L,MA Amanatul Ummah,Jawa Timur,Kota Surabaya,Biologi,SMA,SMA,11.0,Partisipan,Tidak Ada,2016
1,1,Muhammad Khairul Ihsan,L,MAN 1 Banda Aceh,Aceh,Kota Banda Aceh,Ekonomi,SMA,SMA,11.0,Partisipan,Tidak Ada,2021
2,2,Farhannur,L,MAN 1 Banda Aceh,Aceh,Kota Banda Aceh,Ekonomi,SMA,SMA,11.0,Emas,Tidak Ada,2022
3,3,Muhammad Fathoni,L,MAN 1 Banda Aceh,Aceh,Kota Banda Aceh,Fisika,SMA,SMA,11.0,Partisipan,Tidak Ada,2022
4,4,Rahmat MI,L,MAN 1 Banda Aceh,Aceh,Kota Banda Aceh,Kimia,SMA,SMA,11.0,Partisipan,Tidak Ada,2022
...,...,...,...,...,...,...,...,...,...,...,...,...,...
19309,19309,Andhika Pratama Wiendassa,L,SMPN Model Terpadu Madani,Sulawesi Tengah,Kota Palu,IPS,SMP,SMP,8.0,Perunggu,Tidak Ada,2024
19320,19320,Hindun Maitsa Amin,P,SMPN Sungai Jauh,Sumatera Selatan,Kab. Musi Rawas Utara,IPS,SMP,SMP,8.0,Partisipan,Tidak Ada,2024
19321,19321,Julia,P,SMPN Sungai Jauh,Sumatera Selatan,Kab. Musi Rawas Utara,IPS,SMP,SMP,8.0,Partisipan,Tidak Ada,2024
19322,19322,Fitri Julia Simamora,P,SMPN 4 Doloksanggul,Sumatera Utara,Kab. Humbang Hasundutan,Matematika,SMP,SMP,7.0,Partisipan,Tidak Ada,2024
19324,19324,Mely Winda Sihite,P,SMPN 4 Doloksanggul,Sumatera Utara,Kab. Humbang Hasundutan,Matematika,SMP,SMP,7.0,Partisipan,Tidak Ada,2024

mengubah data yang sudah clean kedalam csv untuk selanjutnya di kerjakan seluruhnya dalam spreadsheet

In [20]:
df.to_csv('osn_data_cleaned.csv', index=False)